### ISSUE TITLE
RC Connection

### ISSUE THREAD

**Issue by alu454** [jasonbohlinger/cpsc354RCCar#1]
I think that this very interesting, and shows good visual representation of the car's motion, but I'm a little confused on how this connects to an RC car?

**Comment by jasonbohlinger** [comment]
Hi Alan, our plan is to use serial communication (done via Arduino application and signal wires) to load the code generated from our website onto the hardware of the RC car. The current code generated is Python, but the Arduino C function names and headers are nearly identical, making the shift to generating Arduino C code extremely easy.
