### ISSUE TITLE
RCCar Start and Stop

### ISSUE THREAD

**Issue by kango20** [jasonbohlinger/cpsc354RCCar#2]
I really like the idea of your project. I noticed there are only three blocks with loop, move forward, and turn. Would there be any implementation to start up and stop the car strictly from Blockly so the user will have complete control of the car instead of only movements?

**Comment by jasonbohlinger** [comment]
Each time the program is loaded onto the Arduino, the car will be powered on, so that is constant throughout our programs. However, we have implemented a stop block as of #6
