### ISSUE TITLE
Blockly Blocks "Movement Section"

### ISSUE THREAD

**Issue by thomasogawa** [jasonbohlinger/cpsc354RCCar#4]
I really like how you guys all your blocks encompassed in a "movement" section. However, I noticed that whenever I drag a block form the toolbox the movement it then closes up the "movement" section and I have to open it up again which gets a bit tedious. So maybe finding a way to keep the section opened so you don't need to open it again each time you drag a block on.

**Comment by jasonbohlinger** [comment]
Commit ceb8e04 added the change you suggested, thank you!
